name: Vulnerability Analysis

on:
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Execute Script
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        COMPONENT_KEY: ${{ secrets.COMPONENT_KEY }}
        GITHUB_REPO: ${{ secrets.GH_REPO }}
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        OPENAI_API_URL: ${{ secrets.OPENAI_API_URL }}
        OPENAI_API_TOKEN: ${{ secrets.OPENAI_API_TOKEN }}
        OPENAI_API_ENGINE: ${{ secrets.OPENAI_API_ENGINE }}
      run: python3 sonar-codefix.pyc --sonar-token $SONAR_TOKEN --component-key $COMPONENT_KEY --github-repo $GITHUB_REPO --github-token $GITHUB_TOKEN --openai-api-url $OPENAI_API_URL --openai-api-token $OPENAI_API_TOKEN --openai-api-engine $OPENAI_API_ENGINE
